title: James — Portfolio
description: >-
  Portfolio of James Vickers, a Computer Science student at Victoria University of
  Wellington
baseurl: ""
url: "https://jamesrvickers.github.io/"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE
  - node_modules
